services:
  app:
    container_name: carenet
    image: carenet:latest
    env_file:
      - .env.production
    expose:
      - 3000
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.carenet.rule=Host(`carenet.cemi.re.kr`)"
      - "traefik.http.routers.carenet.entrypoints=websecure"
      - "traefik.http.routers.carenet.tls.certresolver=cf"
      - "traefik.http.routers.carenet.middlewares=TmNoAiBotsMiddleware@file"
      - "traefik.http.services.carenet.loadbalancer.server.port=3000"
    restart: unless-stopped
    networks:
      - default
      - traefik-net

networks:
  default:
    driver: bridge
  traefik-net:
    external: true
